<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\UniGate.SharedKernel\UniGate.SharedKernel.csproj" />
    <ProjectReference Include="..\UniGate.Notifications.Domain\UniGate.Notifications.Domain.csproj" />
  </ItemGroup>

</Project>
